### ISSUE TITLE
Console error when a player logs on after a reboot and a game hasn't been started

### ISSUE THREAD

**Issue by shantek** [shantek/UltimateBingo#34]
If a player logs on after a reboot and the game has never been started, the following error is thrown in the console.

ERROR Could not pass event PlayerJoinEvent to UltimateBingo v0.7.1
14.05 21:28:57 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "this.bingoGUIs" is null
14.05 21:28:57 [Server] INFO at io.shantek.managers.BingoManager.checkHasBingoCard(BingoManager.java:99) ~[UltimateBingo-0.7.1.jar:?]
14.05 21:28:57 [Server] INFO at io.shantek.listeners.BingoPlayerJoinListener.onJoin(BingoPlayerJoinListener.java:36) ~[UltimateBingo-0.7.1.jar:?]
14.05 21:28:57 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor6.execute(Unknown Source) ~[?:?]
14.05 21:28:57 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
14.05 21:28:57 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-493]
14.05 21:28:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
14.05 21:28:57 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-493]
14.05 21:28:57 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-493]
14.05 21:28:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
14.05 21:28:57 [Server] INFO at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:345) ~[paper-1.20.4.jar:git-Paper-493]
14.05 21:28:57 [Server] INFO at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:134) ~[paper-1.20.4.jar:git-Paper-493]
14.05 21:28:57 [Server] INFO at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.4.jar:git-Paper-493]
14.05 21:28:57 [Server] INFO at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.4.jar:git-Paper-493]

**Comment by shantek** [comment]
Resolved in 0.7.1
