### ISSUE TITLE
Error starting flying game on 1.20.6 Spigot server

### ISSUE THREAD

**Issue by shantek** [shantek/UltimateBingo#36]
Starting a flying game on Spigot 1.20.6 throws the following error

23.05 07:16:13 [Server] Server thread/WARN [UltimateBingo] Task #1448 for UltimateBingo v0.7.1 generated an exception
23.05 07:16:13 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.effects" is null
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftMetaFirework.applyToItem(CraftMetaFirework.java:189) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:638) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:611) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftItemStack.<init>(CraftItemStack.java:104) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftItemStack.<init>(CraftItemStack.java:97) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftItemStack.asCraftCopy(CraftItemStack.java:76) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftInventory.firstPartial(CraftInventory.java:273) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftInventory.addItem(CraftInventory.java:302) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at io.shantek.tools.BingoFunctions.equipLoadoutGear(BingoFunctions.java:307) ~[?:?]
23.05 07:16:13 [Server] INFO at io.shantek.BingoCommand.lambda$startBingo$7(BingoCommand.java:279) ~[?:?]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:13 [Server] INFO at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:15 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1397) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:15 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:15 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:15 [Server] INFO at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]
23.05 07:16:15 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4171-Spigot-342f493-87d0a33]

**Comment by shantek** [comment]
This has now been resolved.
